name: "Backend Tech Debt"
projects: ["MobileArts/4"]
description: Track refactors, cleanup, or upgrades
labels: ["area:backend", "type:tech-debt"]
title: "[BE][TechDebt]: "
body:
  - type: input
    id: service
    attributes:
      label: Service / Module
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What’s painful now (maintainability, risk, cost)?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Work
      description: Refactor plan, scope, and acceptance criteria

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Business priority for scheduling
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true